age=(input("enter your age:"))
name=(input("enter your name:"))
surname=(input("enter your surname:"))
favcolor=(input("enter your favorite color:"))
height=(input("enter your height:"))
print(("my name is ") + (name) + " " + (surname) + ", " + "my height is " + (height) + ", " + "age is " + (age) + " and favorite color is " + (favcolor) + ".")